# Generated by Django 5.2.9 on 2025-12-04 01:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('posture_status', models.CharField(choices=[('good', 'Good Posture'), ('bad', 'Bad Posture')], max_length=10)),
                ('angle', models.FloatField(help_text='Hip angle in degrees')),
                ('duration', models.IntegerField(default=0, help_text='Duration in seconds')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='posture_str_timesta_6d850f_idx'), models.Index(fields=['posture_status', '-timestamp'], name='posture_str_posture_6620fd_idx')],
            },
        ),
    ]
